### PR TITLE
throw err when data size too big for largest qr code

### PR DESCRIPTION
**Pull request by ongspxm**
```
Currently, for input data that exceeds the data size possible for the
qrcode, a blank canvas or image will be returned without any error
thrown.

For applications that uses this library, it might be hard for them to
know that an error occurred in the qrcode generation.

Let's alter the qr code generation process to throw the "code length
overflow" error is thrown after it has tried all the versions of the
qrcode.
```

### CODE REVIEW

**Comment by rugk** [comment]
Note: Used for https://github.com/rugk/offline-qr-code/pull/168, as a requirement for https://github.com/rugk/offline-qr-code/issues/72 in the [Offline QR Code Generator add-on](https://github.com/rugk/offline-qr-code).

**Review by rugk — COMMENTED** [review]
I don't know whether updating `package-lock.json` is really what @lrsjng wants…

**Comment by ongspxm** [comment]
@lrsjng ready for review

**Comment by lrsjng** [comment]
@ongspxm thank you and sorry for the delay!

**Pull request merged**
